DROP TABLE locations;
create table locations (
	location_id DECIMAL(4,0),
	street_address VARCHAR(40),
	postal_code VARCHAR(12),
	city VARCHAR(30),
	state_province VARCHAR(25),
	country_id VARCHAR(2)
);
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.6422, '900 Onsgard Terrace', null, 'Gaojingzhuang', null, 'CN');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.0542, '461 Schlimgen Junction', null, 'Taiyang', null, 'CN');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.6976, '65939 Stephen Parkway', null, 'Dhamār', null, 'YE');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.3599, '31 Tomscot Circle', null, 'Lapai', null, 'NG');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.0074, '320 Autumn Leaf Street', '59762', 'Francisco J Mujica', 'Michoacan De Ocampo', 'MX');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.5505, '0456 Brickson Park Trail', null, 'Wangqinzhuang', null, 'CN');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.3572, '1492 Donald Way', null, 'Lincheng', null, 'CN');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.6185, '4 Monument Center', null, 'Viraco', null, 'PE');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.3072, '37 Sheridan Terrace', null, 'Chenyangzhai', null, 'CN');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.1431, '59 Sugar Avenue', '64103', 'San Antonio', 'Nuevo Leon', 'MX');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.7531, '93 Packers Road', null, 'Banyumas', null, 'ID');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.8799, '55900 Michigan Park', '4765-122', 'Novais', 'Braga', 'PT');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.4934, '63198 Glendale Lane', null, 'Wedoro', null, 'ID');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.7977, '4703 Weeping Birch Lane', '72240', 'Nong Yasai', null, 'TH');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.3636, '95058 Sunnyside Place', null, 'Nurota Shahri', null, 'UZ');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.4655, '00153 Kedzie Trail', '1121', 'København', 'Region Hovedstaden', 'DK');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.2459, '726 Browning Junction', null, 'Houxiang', null, 'CN');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.7951, '422 Starling Plaza', null, 'Jingyang', null, 'CN');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.7694, '2 Maywood Way', null, 'Oekefan', null, 'ID');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.6456, '4663 Bluejay Way', '24118', 'Kiel', 'Schleswig-Holstein', 'DE');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.5774, '55373 Schurz Crossing', null, 'Zhouling', null, 'CN');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.4669, '31 Hoard Place', '1532', 'København', 'Region Hovedstaden', 'DK');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.159, '0008 Hooker Center', null, 'Longshan', null, 'CN');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.0941, '82 Westerfield Crossing', '62930-000', 'Limoeiro do Norte', null, 'BR');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.533, '28 Montana Road', null, 'Budakovo', null, 'XK');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.1664, '677 Hagan Center', null, 'Jangheung', null, 'KR');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.1661, '3 Eagan Plaza', '788 15', 'Velké Losiny', null, 'CZ');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.2129, '5 Boyd Park', '74311 CEDEX', 'Cluses', 'Rhône-Alpes', 'FR');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.0161, '17609 Armistice Trail', '2800-011', 'Almada', 'Setúbal', 'PT');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.6083, '75681 Leroy Place', null, 'Curahuasi', null, 'PE');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.4152, '1 Autumn Leaf Center', '17029 CEDEX 1', 'La Rochelle', 'Poitou-Charentes', 'FR');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.4271, '18054 Southridge Hill', '383 24', 'Mönsterås', 'Kalmar', 'SE');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.1414, '97516 Melrose Trail', '71326', 'Valvedditturai', null, 'LK');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.9534, '3432 Mandrake Way', null, 'Mesiméri', null, 'GR');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.424, '6 Sauthoff Junction', '301086', 'Rodniki', null, 'RU');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.5578, '49 Hayes Hill', 'S9X', 'Meadow Lake', 'Saskatchewan', 'CA');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.0224, '5269 8th Crossing', null, 'Vil’nyans’k', null, 'UA');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.805, '0128 8th Court', null, 'Liuzhi', null, 'CN');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.1166, '996 Maple Wood Way', 'R56', 'Old Kilcullen', null, 'IE');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.0022, '534 Loomis Way', null, 'Abomsa', null, 'ET');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.2906, '6223 Towne Parkway', '150867', 'La Uvita', null, 'CO');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.3792, '7 Graedel Lane', null, 'Shishan', null, 'CN');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.5334, '97318 Dahle Crossing', null, 'Baisha', null, 'CN');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.0593, '38 Ronald Regan Court', '591 71', 'Motala', 'Östergötland', 'SE');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.428, '2 Thompson Place', null, 'Denyshi', null, 'UA');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.1009, '65751 Mosinee Road', '2725-094', 'Mem Martins', 'Lisboa', 'PT');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.7188, '81 Amoth Street', '169060', 'Mikun’', null, 'RU');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.6663, '010 Northland Alley', '7202', 'Tudela', null, 'PH');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.4726, '64752 Almo Parkway', '6149', 'Wellington', null, 'NZ');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.191, '1 Petterle Pass', null, 'Tisco', null, 'PE');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.4957, '04 Debra Center', null, 'Pasirreungit', null, 'ID');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.2914, '2924 Clemons Pass', '929-0203', 'Matsutō', null, 'JP');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.0014, '4133 Havey Place', '352574', 'Mostovskoy', null, 'RU');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.2407, '0 Boyd Trail', null, 'Farīmān', null, 'IR');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.9765, '056 Packers Drive', '999-6861', 'Yamada', null, 'JP');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.1055, '8660 Warrior Way', '7090-021', 'Alcáçovas', 'Évora', 'PT');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.1627, '9771 Hooker Road', null, 'Campechuela', null, 'CU');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.2667, '46838 Orin Alley', null, 'Dikirnis', null, 'EG');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.1242, '1549 Talmadge Park', '142717', 'Vidnoye', null, 'RU');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.6711, '24 Lakewood Crossing', null, 'Doba', null, 'TD');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.522, '44 4th Street', '4465', 'Lesichevo', null, 'BG');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.4228, '8266 Golf Course Way', '90030', 'Los Angeles', 'California', 'US');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.8606, '2416 Jenifer Trail', null, 'Kuandian', null, 'CN');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.3863, '96 Maywood Plaza', '736 01', 'Bohumín', null, 'CZ');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.663, '96212 Kingsford Place', null, 'Dhangarhi', null, 'NP');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.2684, '93 Park Meadow Road', '99-307', 'Strzelce', null, 'PL');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.1514, '480 Crownhardt Hill', '51512', 'Njivice', null, 'HR');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.2289, '827 Loftsgordon Parkway', '70533', 'Guadalupe', 'Oaxaca', 'MX');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.0122, '10 Fremont Center', '4610-572', 'Lameira', 'Porto', 'PT');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.9467, '1 Talisman Alley', null, 'Nyamanari', null, 'GM');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.7469, '0 North Street', '0921', 'Pidsandawan', null, 'PH');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.5394, '78 Oriole Road', '08-400', 'Garwolin', null, 'PL');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.9695, '7 Summerview Park', '12140', 'Lat Lum Kaeo', null, 'TH');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.1632, '42572 Merry Street', null, 'Empório', null, 'GR');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.7161, '599 Union Alley', '58701', 'Sulkava', null, 'FI');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.8262, '8554 Dunning Lane', '673-1236', 'Sandachō', null, 'JP');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.0243, '0 Logan Court', null, 'Sukamulya', null, 'ID');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.163, '578 Starling Point', '7220-043', 'Alqueva', 'Évora', 'PT');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.1805, '702 Village Road', null, 'Guozhai', null, 'CN');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.5445, '87 Scott Way', null, 'Xinchenglu', null, 'CN');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.3128, '16400 Arizona Road', null, 'Walahir', null, 'ID');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.5532, '7 Warbler Street', '3921', 'Brusartsi', null, 'BG');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.1076, '113 Warbler Circle', null, 'Rammūn', null, 'PS');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.8039, '13 Lakewood Gardens Drive', '164200', 'Nyandoma', null, 'RU');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.298, '33 Mccormick Center', null, 'Mala Danylivka', null, 'UA');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.3593, '06 Arkansas Junction', null, 'Pucallpa', null, 'PE');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.3053, '356 Prairieview Terrace', '87-220', 'Radzyń Chełmiński', null, 'PL');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.3155, '31 Merchant Way', null, 'Makīnsk', null, 'KZ');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.5629, '4 Leroy Place', null, 'Traiguén', null, 'CL');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.1463, '69 Pierstorff Pass', null, 'Velykyi Bereznyi', null, 'UA');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.8193, '37685 1st Lane', '94263', 'Sacramento', 'California', 'US');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.0961, '0866 Barnett Plaza', null, 'Delingha', null, 'CN');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.8463, '138 Caliangt Park', null, 'Qingtang', null, 'CN');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.1243, '9 Scoville Road', '42335 CEDEX', 'Roanne', 'Rhône-Alpes', 'FR');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.4982, '21120 Golf Course Pass', '60160', 'Tha Tako', null, 'TH');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.6647, '8974 Kenwood Drive', '33000', 'Rezovac', null, 'HR');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.107, '00 Messerschmidt Place', null, 'San Agustin', null, 'PE');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.9869, '36 Westerfield Drive', '57301', 'Kabīrwāla', null, 'PK');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.2457, '6094 Hanover Terrace', '26-050', 'Kaniów', null, 'PL');
insert into locations (location_id, street_address, postal_code, city, state_province, country_id) values (0.5938, '45 Bunting Plaza', null, 'Bailadores', null, 'VE');

ALTER TABLE locations
ADD region_id  DECIMAL DEFAULT 0;